# -*- coding: utf-8 -*-
"""task_3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xB_i74h7K4wki1ORIM_uv8cmUWUHOYhR
"""

pip install requests beautifulsoup4 pandas openpyxl

import requests
from bs4 import BeautifulSoup

# Step 1: Take product name as input
search = input("Enter product to search on Flipkart: ").replace(" ", "+")

# Step 2: Create search URL
url = f"https://www.flipkart.com/search?q={search}"

# Step 3: Send request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}
response = requests.get(url, headers=headers)

# Step 4: Parse the HTML
soup = BeautifulSoup(response.text, 'html.parser')

# Flipkart product blocks are inside divs with specific class names
products = soup.find_all("div", {"class": "_1AtVbE"})

names = []
prices = []
ratings = []

for product in products:
    name_tag = product.find("div", {"class": "_4rR01T"})  # product name
    price_tag = product.find("div", {"class": "_30jeq3 _1_WHN1"})  # price
    rating_tag = product.find("div", {"class": "_3LWZlK"})  # rating

    if name_tag and price_tag:
        names.append(name_tag.text.strip())
        prices.append(price_tag.text.strip())
        ratings.append(rating_tag.text.strip() if rating_tag else "No Rating")

import pandas as pd

df = pd.DataFrame({
    'Product Name': names,
    'Price': prices,
    'Rating': ratings
})

# Save to Excel
df.to_excel('flipkart_products.xlsx', index=False)
print("✅ Data saved to flipkart_products.xlsx")

from google.colab import files
files.download('flipkart_products.xlsx')

